### ISSUE TITLE
Method overwrite warning

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/Parquet.jl#15]
Whenever I load Parquet with ``using Parquet``, I get this warning:
````
WARNING: Method definition copy!(T, T) in module Thrift at C:\Users\anthoff\.julia\v0.6\Thrift\src\base.jl:591 overwritten in module ProtoBuf at C:\Users\anthoff\.julia\v0.6\ProtoBuf\src\utils.jl:15.
````
Looking at those definitions, they look pretty type-piracy to me, so maybe the right solution would be to just give them some other name in these packages and not add these methods to ``Base.copy!`` in the first place?

**Comment by tanmaykm** [comment]
I think it may be better for `Thrift` and `ProtoBuf` to have abstract base types which their respective generated types extend.
