### ISSUE TITLE
Enable AppVeyor and add a badge

### ISSUE THREAD

**Issue by scls19fr** [JuliaComputing/Parquet.jl#17]
Hello,

I wonder if Parquet is test against julia 0.6 and Windows.
If that's the case maybe you should add an AppVeyor badge

Kind regards

**Comment by davidanthoff** [comment]
I just want to second that! I'm seeing errors on 32 bit Windows over at https://github.com/davidanthoff/ParquetFiles.jl, and it would be really helpful if Parquet.jl was also tested on Windows.
