### ISSUE TITLE
julia 0.7/1.0 compat

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/Parquet.jl#24]
@tanmaykm any chance we might be able to get a julia 0.7/1.0 compatible version?

**Comment by tanmaykm** [comment]
WIP here: https://github.com/JuliaComputing/Parquet.jl/pull/25.

At the moment we need a MemPool.jl release for Julia 0.7/1.0 to proceed further.

**Comment by davidanthoff** [comment]
Is there more work needed for MemPool.jl? Or just a tag?

**Comment by tanmaykm** [comment]
This is fixed now with #26. Will close in a bit.
