### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by femtotrader** [JuliaComputing/Parquet.jl#5]
https://travis-ci.org/JuliaComputing/Parquet.jl
and
https://travis-ci.org/tanmaykm/Parquet.jl

are not active repositories

so Travis should be enabled

Badge should be changed
https://github.com/JuliaComputing/Parquet.jl/blame/master/README.md#L3

**Comment by femtotrader** [comment]
AppVeyor should also be used to test agains Windows

**Comment by tanmaykm** [comment]
resolved (ref #7)
