### ISSUE TITLE
Julia 0.6 support for Parquet.jl

### ISSUE THREAD

**Issue by femtotrader** [JuliaComputing/Parquet.jl#6]
Parquet.jl is currently broken with Julia 0.6

**Comment by femtotrader** [comment]
Required by https://github.com/davidanthoff/IterableTables.jl/issues/49

**Comment by femtotrader** [comment]
Snappy is currently broken with Julia 0.6
https://github.com/bicycle1885/Snappy.jl/issues/6
so it should first be fixed

**Comment by femtotrader** [comment]
Snappy is now fixed for Julia 0.6

**Comment by femtotrader** [comment]
Zlib is required but it doesn't seem to support Julia 0.6.
They suggest to use Libz https://github.com/BioJulia/Libz.jl but we can see

    NOTE: If you are starting a new project on Julia 0.6 or later, it is recommended to use the CodecZlib.jl package instead.

so maybe you should use https://github.com/bicycle1885/CodecZlib.jl

**Comment by femtotrader** [comment]
[LRUCache](https://github.com/jcrist/LRUCache.jl) is [required](https://github.com/JuliaComputing/Parquet.jl/blob/master/REQUIRE#L6) but is currently broken for Julia 0.6 (see https://github.com/jcrist/LRUCache.jl/issues/3 )

**Comment by tanmaykm** [comment]
Julia 0.6 is supported now
