### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/Parquet.jl#7]
@tanmaykm and @ViralBShah?

I think it would be super useful (see e.g. https://discourse.julialang.org/t/what-fileformat-to-use-to-load-data-for-high-performance-computing/4786), and I'd be happy to integrate it with the whole data stack I created over the last year, but first we would need to get it to work on julia 0.6, and I won't have the time for that.

**Comment by ViralBShah** [comment]
We do want to use this. @tanmaykm Any ideas when you might be able to get this to 0.6?

cc @aviks

**Comment by tanmaykm** [comment]
Sure. Can so that sometime next week.

**Comment by davidanthoff** [comment]
Cool!

**Comment by davidanthoff** [comment]
Bump, any update?

**Comment by tanmaykm** [comment]
I started to get some of the dependencies fixed/removed. Unfortunately haven't been able to spend a lot of time on this yet.

**Comment by davidanthoff** [comment]
Cool, thanks for the update!

**Comment by davidanthoff** [comment]
Alright, I think we are in really good shape now. I've got Snappy.jl to work on all platforms, just waiting for a  PR to be merged over there and then a new tag. Then we need to merge the open PRs here in the repo, and then this can be registered in METADATA, right?

I'm also done with the full iterable tables and FileIO.jl integration: https://github.com/davidanthoff/ParquetFiles.jl, that just requires a that this repo here is registered.

**Comment by davidanthoff** [comment]
Snappy.jl now is tagged with full platform support (Linux, Win, Mac etc.).

So I think this package could be registered in METADATA.jl now? Anything still holding that back? I have some downstream stuff that I'd like to move forward that depends on this being in METADATA.jl, so would be great if we could move with this.

Oh, and can someone please enable app veyor for this repo?

**Comment by tanmaykm** [comment]
I don't have privileges to enable appveyor. Maybe @mdpradeep can?

cc @aviks

**Comment by davidanthoff** [comment]
Bump, anything holding up package registration and appveyor-on?

**Comment by ViralBShah** [comment]
Ah - I did give @tanmaykm privileges, but forgot to mention it here.

**Comment by tanmaykm** [comment]
@ViralBShah sorry, I don't seem to have access yet.

**Comment by quinnj** [comment]
I think someone w/ the right JuliaComputing access just needs to go to https://github.com/apps/attobot/installations/new and configure this repo. Similarly at https://ci.appveyor.com/projects for appveyor

**Comment by ViralBShah** [comment]
I made everyone at JC owners of everything!

**Comment by davidanthoff** [comment]
Yay, thank you all :)
