### ISSUE TITLE
Investigate whether Blosc.jl could be used instead of Snappy.jl

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/Parquet.jl#9]
Snappy.jl currently doesn't work on Windows. Maybe https://github.com/stevengj/Blosc.jl could be used instead, at least the original underlying C version seems to support the snappy compression algorithm.

**Comment by stevengj** [comment]
It's more that the C version allows linking to and calling the snappy library.  You still need to compile the snappy library for windows.

**Comment by davidanthoff** [comment]
[This](https://github.com/Blosc/c-blosc#codec-support-with-cmake) seems to suggest that the snappy source is just included by default in the blosc stuff? And the source seems to be [here](https://github.com/Blosc/c-blosc/tree/master/internal-complibs/snappy-1.1.1)? So maybe one strategy would be to modify https://github.com/stevengj/Blosc.jl/blob/master/deps/make.blosc to also include snappy?

**Comment by davidanthoff** [comment]
Ah, I see that this has been discussed in https://github.com/stevengj/Blosc.jl/issues/3.

Just as a follow up to your other comment on the forum: my understanding is that snappy is one of the supported compressions for parquet files, and I haven't seen bosc (the algorithm) mentioned there. So I think we actually need to get a snappy decompression working on windows if want to get parquet working on Windows.

**Comment by stevengj** [comment]
We can certainly add it, thought it's not clear to me why it is easier to build here than in Snappy.jl

**Comment by davidanthoff** [comment]
We would free ride on you maintaining Blosc.jl and having figured out the cross-compilation stuff. The maintainer of Snappy.jl doesn't have a Windows machine and won't add windows support, and I don't really know how the whole cross-compilation stuff works.

Besides that, there might be another benefit: I think Blosc could also include zlib support, right? In that case Parquet.jl could also cut down on the number of dependencies, because Blosc.jl could just be the one package that handles all decompression.

**Comment by davidanthoff** [comment]
See stevengj/Blosc.jl#44, if that gets merged we should have a snappy decompressor that works on Windows.

**Comment by stevengj** [comment]
Note that stevengj/Blosc.jl#44 doesn't completely address this.  It would allow you to use the Snappy compressor *via the Blosc API*, but that will still embed [the *blosc* header](https://github.com/Blosc/c-blosc/blob/master/README_HEADER.rst) at the beginning of the compressed blocks.

You may still have to call the underlying Snappy C API directly in order to access the raw compressed data.

Or I guess you could compress it with the Blosc API and then just skip the first 16 bytes (the header) when you write compressed data, and add back the 16-byte header manually when reading the compressed data?   I guess that wouldn't be hard.

**Comment by stevengj** [comment]
Also, one would have to be careful of things like Blosc's byte-shuffling algorithm, which it may still do if it uses Snappy?   This can be disabled, though.

**Comment by davidanthoff** [comment]
Right now this package only reads files, so we would only use the decompression. But if that also requires the blosc header, this plan won't work. I'll try it later. 

Having said that, I think I got enough of an idea how the cross compile works from @stevengj at this point that I could also just add win binaries to Snappy.jl, I think.

**Comment by stevengj** [comment]
You can also just `ccall` the snappy functions in libblosc.

**Comment by davidanthoff** [comment]
I'm going to close this, we got the complete cross-compile for Snappy.jl working (based on BinaryBuilder.jl and BinaryProvider.jl), so this package here can just continue to use Snappy.jl.
